version: '3.8'

services:
  app:
    build: .
    ports:
      - '4555:3000'
    env_file:
      - .env
    depends_on:
      - db
      # - redis
    command: ['npm', 'start']
    # networks:
    #   - backend

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
#     networks:
#       - backend

#   redis:
#     image: 'redis:latest'
#     ports:
#       - '6379:6379'
#     networks:
#       - backend

# networks:
#   backend:
#     driver: bridge
